### ISSUE TITLE
Resulting matrices end up being dense

### ISSUE THREAD

**Issue by begab** [yogarshi/bisparse#1]
First of all thanks for releasing this code!
I was trying to reproduce the sparse embeddings for French and English using the sample data and the suggested hyperparameters (`mu_fr=mu_en=0.5 and mu_xling=10, output_size=100`), however, all of the matrices in the solution ended up being dense: both `X_EN_sol` and `X_FR_sol` contained roughly 1% of zeros only.
As a potential solution, I was giving a variety of hyperparameters a try, but did not manage to obtain a reasonable level of sparsity in the resulting matrices.

I got the below logging about the learning procedure when run with the suggested hyperparameters. Can you see any peculiarity in it or do you have any suggestion what should I do differently to get sparse matrices?

>     FASTA:	mode = adaptive
> 	maxIters = 10,	tol = 1e-07
>     1: resid = 4.6e+08, backtrack = 2, tau = 7.96609e-07
>     2: resid = 1.8e+05, backtrack = 0, tau = 7.96037e-07
>     3: resid = 6.5e+04, backtrack = 0, tau = 8.62699e-07
>     4: resid = 6.3e+04, backtrack = 0, tau = 1.87536e-05
>     5: resid = 5.9e+04, backtrack = 0, tau = 0.000242865
>     6: resid = 8.1e+04, backtrack = 2, tau = 8.8587e-06
>     7: resid = 7.3e+05, backtrack = 0, tau = 8.62277e-07
>     8: resid = 1.6e+04, backtrack = 0, tau = 8.62263e-07
>     9: resid = 1.6e+04, backtrack = 0, tau = 0.00060079
>     10: resid = 1.3e+04, backtrack = 0, tau = 0.00112266
>     	Done:  time = 288.761 secs, iterations = 10

**Comment by yogarshi** [comment]
Hi! Thanks for you interest in the code.

One thing that you should definitely do is crank up the number of iterations, since the number 10 was just a placeholder. In my experience, you typically need at least 100 iterations to get reasonable results, and closer to 500 iterations if you want to be really confident. Let me know if that doesn't solve it. I'll keep the issue open in the mean time.

**Comment by begab** [comment]
I tried to increase the iteration number previously but did not go beyond the 100s range. Now that I tried your suggestion and went for 500 iterations I managed to obtain matrices with 60-70% of zero values. Thank you for helping me fixing this.
